import { defineConfig } from 'vite'

// load 钩子：自定义模块的加载逻辑
// 这里我们让 import 一个 .info 文件时，返回自定义的 JS 内容
function loadPlugin() {
  return {
    name: 'load-plugin',
    load(id) {
      if (id.endsWith('.info')) {
        console.log('[load-plugin] load:', id)
        // 返回一段 JS 源码
        return `
export default {
  loadedAt: ${Date.now()},
  message: 'This module is generated by load hook',
  id: ${JSON.stringify(id)}
}
`
      }
      return null
    },
  }
}

export default defineConfig({
  plugins: [loadPlugin()],
})
